#!/usr/bin/env bash
# This script displays "Best School"

result=1

while [ $result -le 10 ]
	do
		if [ $result -eq 4 ]; then
			echo "bad luck"
		elif [ $result -eq 8 ]; then
			echo "good luck"
		else
			echo "Best School"
		fi

		((result++))
	done
