#!/usr/bin/env bash
# This script is about clock

hour=0
minutes=1

while [ $hour -le 12 ]
	do
		echo "hour: $hour"
		((hour++))

		while [ $minutes -le 59 ]
			do
				echo $minutes
				((minutes++))
			done
			((minutes = 1))
			
	done
